repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.6
    hooks:
      - id: ruff
        name: ruff import sorting
        args: [--select, I, --fix]
        types: [python]

      - id: ruff
        name: ruff lint (auto-fix)
        args: [--fix, --exit-non-zero-on-fix]
        types: [python]
        exclude: ^(migrations|docs)/

      - id: ruff-format
        name: ruff format
        types: [python]
        exclude: ^(migrations|docs)/

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-json
